name = "Spring"
uuid = "e4e52cb7-b512-490f-82be-bf6acab770af"
authors = ["Laurent Plagne <laurent.plagne@triscale-innov.com>"]
version = "0.1.0"

[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
